"""user-table

Revision ID: 750ffd3104d7
Revises: 
Create Date: 2020-03-10 11:44:46.189111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750ffd3104d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.Column('deleteToken', sa.String(length=100), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('middleName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=True),
    sa.Column('secret', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
