"""shortner_user_zookeeper_analytics_base_migration

Revision ID: aabf843e7b40
Revises: 
Create Date: 2020-03-14 18:02:42.192393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabf843e7b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'seeds',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('next_seed', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'shortner',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('long_url', sa.Text(), nullable=False),
        sa.Column('url_hash', sa.String(length=20), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('hit_count', sa.Integer(), nullable=False),
        sa.Column('delete_token', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url_hash', 'delete_token', name='uq_shortner_url_hash_delete_token')
    )
    op.create_index(op.f('ix_shortner_url_hash'), 'shortner', ['url_hash'], unique=False)
    op.create_table(
        'url_shortening_daily_count',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('success_count', sa.Integer(), nullable=False),
        sa.Column('failed_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_shortening_daily_count_date'), 'url_shortening_daily_count', ['date'], unique=False)
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('middle_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('primary_phone', sa.String(length=20), nullable=True),
        sa.Column('secret', sa.String(length=100), nullable=True),
        sa.Column('account_status', sa.String(length=50), nullable=False),
        sa.Column('delete_token', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email', 'delete_token', name='uq_users_email_delete_token'),
        sa.UniqueConstraint('username', 'delete_token', name='uq_users_username_delete_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_url_shortening_daily_count_date'), table_name='url_shortening_daily_count')
    op.drop_table('url_shortening_daily_count')
    op.drop_index(op.f('ix_shortner_url_hash'), table_name='shortner')
    op.drop_table('shortner')
    op.drop_table('seeds')
    # ### end Alembic commands ###
